import { Food } from "./app/shared/models/food";
import { Tag } from "./app/shared/models/tag";

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pizza Mediterranea',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Italian'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Pizza Capresse',
    price: 10,
    cookTime: '10-20',
    favorite: true,
    origins: ['Italian'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'3',
    name: 'Pizza Peperoni',
    price: 10,
    cookTime: '10-20',
    favorite: false,
    origins: ['us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'4',
    name: 'Pizza Hawaina',
    price: 10,
    cookTime: '10-20',
    favorite: true,
    origins: ['Hawaina'],
    stars: 4.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'5',
    name: 'Pizza Camaron ',
    price: 10,
    cookTime: '10-20',
    favorite: false,
    origins: ['Italian'],
    stars: 4.0,
    imageUrl:'assets/food-5.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'6',
    name: 'Pizza Mexican',
    price: 10,
    cookTime: '10-20',
    favorite: false,
    origins: ['Italian', 'Mexican'],
    stars: 4.0,
    imageUrl:'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Pasta ',
    price: 9,
    cookTime: '10-15',
    favorite: false,
    origins: ['Italian'],
    stars: 4.0,
    imageUrl:'assets/food-7.jpg',
    tags: ['pasta', 'Lunch'],
  },
  {
    id:'8',
    name: 'Salad Vegetarian ',
    price: 9,
    cookTime: '10-15',
    favorite: false,
    origins: [''],
    stars: 4.0,
    imageUrl:'assets/food-8.jpg',
    tags: ['Salad', 'Lunch'],
  },
]

export const sample_tags:Tag[]=[
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 5 },
  { name: 'Pizza', count: 1 },
  { name: 'Lunch', count: 3 },
  { name: 'Salad', count: 1 },
  { name: 'Pasta', count: 1 },
]
